# Generated by Django 3.2.12 on 2022-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Full name')),
                ('subject', models.ManyToManyField(related_name='teacher_subject', to='graphql_app.Subject', verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Full name')),
                ('avg_grade', models.FloatField(verbose_name='Average grade')),
                ('subject', models.ManyToManyField(related_name='student_subject', to='graphql_app.Subject', verbose_name='Subject')),
            ],
        ),
    ]
