# Generated by Django 3.2.12 on 2022-04-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name'], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
